name: CI

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with tokio
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --features "runtime-tokio anyhow" --no-default-features

      - name: Build with eyre
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --features "runtime-tokio eyre" --no-default-features

      - name: Run tests with async-std
        uses: actions-rs/cargo@v1
        with:
          command: test 
          args: --all -- --nocapture

      - name: Run tests with tokio
        uses: actions-rs/cargo@v1
        with:
          command: test 
          args: --all --features "runtime-tokio anyhow" --no-default-features

      - name: Run tests with eyre
        uses: actions-rs/cargo@v1
        with:
          command: test 
          args: --all --features "runtime-tokio eyre" --no-default-features
