name: Pull request

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_commit:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A PR should not contain too many commits
          fetch-depth: 10
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/latest/download/convco-ubuntu.zip | zcat > convco
          chmod +x convco
          ./convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          rm convco


  semver:
    name: cargo-semver-checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - default
          - anyhow, runtime-tokio
          - anyhow, runtime-async-std
          - eyre, runtime-tokio
          - eyre, runtime-async-std
          # - anyhow, runtime-tokio, tracing
          # - anyhow, runtime-async-std, tracing
          # - eyre, runtime-tokio, tracing
          # - eyre, runtime-async-std, tracing
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2.6
        env:
          RUSTFLAGS: --cfg tokio_unstable
        with:
          feature-group: "only-explicit-features"
          features: ${{ matrix.features}}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo-fmt
        run: cargo fmt --all --check

  cargo-deny:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v1
